# Build settings
markdown: kramdown
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "Jak Buttarazzi"
description: > # this means to ignore newlines until "email:"
   Software Engineer at NetApp

email: JakRazzi@gmail.com
#blog logo
logo: "/assets/images/jak-photo.jpg"
pin: "/assets/images/jr-pin.jpg"
# blog cover
cover: "/assets/images/rom-camp.jpg"

name: 'Jak Buttarazzi'
author: 'Jak Buttarazzi'
author_image: "/assets/images/jak-photo.jpg"

paginate:	5

url: "/" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: '@jakrazzi'

#fill in disqus shortname to use disqus
disqus: jakrazzi

# social icons and sharing options
social:
  - icon:	twitter
    url:	
    desc: 
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

  - icon: facebook
    url:  
    desc: 
    share_url: https://www.facebook.com/sharer.php
    share_title: ?t=
    share_link: "&amp;u="

  - icon:	linkedin
    url:	https://linkedin.com/in/jakrazzi
    desc: Connect with me on LinkedIn
    share_url: 
    share_title: 
    share_link: 

  - icon:	github
    url:	https://github.com/jakrazzi
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

  # - icon:	google-plus
  #   url:	https://google.com/jakrazzi
  #   desc:	Add me on google+
  #   share_url:
  #   share_title:
  #   share_link:
